name: deploy to digital ocean

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 600s
          source: frontend
          target: /root/app/

      - name: execute via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 600s
          script: |
            cd /home/app/frontend
            npm install

