name: deploy to digital ocean

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PATH: $PATH:/root/.nvm/versions/node/v18.18.2/bin
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 600s
          source: frontend
          target: /root/app/

      - name: execute via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 600s
          script: |
            echo $PATH
            sudo chown -R root:root /root/app/frontend
            cd /root/app/frontend
            rm -rf /root/app/frontend/node_modules || true
            npm install
            pm2 delete frontend || true
            pm2 start

